services:
  migrate:
    build:
      context: .
      dockerfile: bin/node/docker/Dockerfile
    command: ["migrate", "--database-url", "/app/data/node.db"]
    volumes:
      - node_data:/app/data

  miden-note-transport-node:
    build:
      context: .
      dockerfile: bin/node/docker/Dockerfile
    ports:
      - "57292:57292"  # gRPC
    command: ["serve", "--listen", "0.0.0.0:57292", "--database-url", "/app/data/node.db", "--max-storage-bytes", "1073741824"]
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      - JSON_LOGGING=true
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      - RUST_LOG=INFO
      - DOCKER_ENV=true
    volumes:
      - node_data:/app/data

volumes:
  node_data:
