services:
  miden-note-transport-node:
    build:
      context: .
      dockerfile: bin/node/docker/Dockerfile
    ports:
      - "57292:57292"  # gRPC
    command: ["miden-note-transport-node", "--host", "0.0.0.0", "--database-url", "/app/data/node.db"]
    environment:
      - JSON_LOGGING=true
      - OTEL_EXPORTER_OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      - RUST_LOG=INFO
      - DOCKER_ENV=true
    volumes:
      - node_data:/app/data

volumes:
  node_data:
