use std::env;
use std::path::PathBuf;

use fs_err as fs;
use miette::{Context, IntoDiagnostic};
use prost::Message;

const MNT_DESCRIPTOR: &str = "miden_note_transport_file_descriptor.bin";

/// Writes the API descriptor to `OUT_DIR` and optionally regenerates the Rust bindings.
///
/// Bindings are regenerated only if `BUILD_PROTO` is set to `1`; published builds use the
/// descriptor supplied by the proto-build crate and the committed Rust bindings.
fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo::rerun-if-changed=../../proto/proto");
    println!("cargo::rerun-if-env-changed=BUILD_PROTO");

    let out =
        env::var("OUT_DIR").expect("env::OUT_DIR is always set in build.rs when used with cargo");
    let descriptor = miden_note_transport_proto_build::mnt_api_descriptor();
    let descriptor_path = PathBuf::from(out).join(MNT_DESCRIPTOR);
    fs::write(descriptor_path, descriptor.encode_to_vec())
        .into_diagnostic()
        .wrap_err("writing mnt file descriptor")?;

    if env::var("BUILD_PROTO").as_deref() != Ok("1") {
        return Ok(());
    }

    // Generate the Rust bindings
    tonic_prost_build::configure()
        .out_dir("src/generated")
        .build_server(true)
        .build_client(true)
        .compile_fds_with_config(descriptor, tonic_prost_build::Config::new())
        .into_diagnostic()
        .wrap_err("generating protobuf bindings")?;

    // Generate mod.rs with clippy allows
    generate_mod_rs("src/generated")?;

    Ok(())
}

/// Generate `mod.rs` which includes all files in the folder as submodules.
fn generate_mod_rs(directory: impl AsRef<std::path::Path>) -> std::io::Result<()> {
    let mod_filepath = directory.as_ref().join("mod.rs");

    // Discover all submodules by iterating over the folder contents.
    let mut submodules = Vec::new();
    for entry in fs::read_dir(directory.as_ref())? {
        let entry = entry?;
        let path = entry.path();
        if path.is_file()
            && path.extension().is_some_and(|extension| extension == "rs")
            && path.file_name().unwrap() != "mod.rs"
        {
            let file_stem = path
                .file_stem()
                .and_then(|f| f.to_str())
                .expect("Could not get file name")
                .to_owned();

            submodules.push(file_stem);
        }
    }

    submodules.sort();

    let contents = submodules.iter().map(|f| format!("pub mod {f};\n"));
    let contents = std::iter::once(
        "#![allow(clippy::pedantic, reason = \"generated by build.rs and tonic\")]\n".to_string(),
    )
    .chain(std::iter::once(
        "#![allow(clippy::large_enum_variant, reason = \"generated by build.rs and tonic\")]\n\n"
            .to_string(),
    ))
    .chain(contents)
    .collect::<String>();

    fs::write(mod_filepath, contents)
}
