name: Dry Run Publish Rust Crates

on:
  push:
    branches: [main, next, 'release/**']

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cleanup large tools for build space
        uses: ./.github/actions/cleanup-runner

      - name: Update Rust toolchain
        run: |
          rustup update --no-self-update

      - name: Dry run - publish
        run: |
          cargo publish --workspace --dry-run
